const CONFIGURATOR_DATA = {
  steps: [
    {
      id: 1,
      name: 'Vehicle Selection',
      type: 'select',
      dataKey: 'vehicles',
      required: true,
      configKey: 'vehicle',
      template: 'vehicle-select',
      description: 'Choose your and lets get started!'
    },
    {
      id: 2,
      name: 'Let\'s Select the Build Type',
      type: 'card-select',
      dataKey: 'buildTypes',
      required: true,
      configKey: 'buildType',
      template: 'build-type',
      description: ''
    },
    {
      id: 3,
      name: 'Service Bodies',
      type: 'card-selection',
      dataKey: 'serviceBody',
      required: true,
      configKey: 'serviceBody',
      template: 'service-body',
      description: 'Available in Service Body(single canopy space) or Work Body (two toolboxes with central tunnel and rear door). Choose from textured white or black powder coat.',
      showIf: (config) => config.buildType && ['service-body'].includes(config.buildType.id)
    },
    {
      id: 4,
      name: 'Tray Selection',
      type: 'card-select',
      dataKey: 'trays',
      required: true,
      configKey: 'tray',
      template: 'tray',
      description: 'Tray size is selected based on your vehicle.',
      showIf: (config) => config.buildType && ['tray-only', 'tray-canopy'].includes(config.buildType.id)
    },
    {
      id: 5,
      name: 'Canopy Selection',
      type: 'card-select',
      dataKey: 'canopies',
      required: true,
      configKey: 'canopy',
      template: 'canopy',
      description: '',
      showIf: (config) => config.buildType && ['canopy', 'tray-canopy'].includes(config.buildType.id)
    },
    {
      id: 6,
      name: 'Tray Sides',
      type: 'card-select',
      dataKey: 'traySides',
      required: true,
      configKey: 'traySides',
      template: 'tray-sides',
      description: '',
      showIf: (config) => config.buildType && ['tray-only', 'tray-canopy'].includes(config.buildType.id)
    },
    {
      id: 7,
      name: '12 Volt',
      type: 'volt-oven',
      dataKey: 'voltAndOven',
      configKey: 'voltAndOven',
      template: 'volt-oven',
      description: '',
      showIf: (config) => config.buildType && ['tray-canopy', 'canopy', 'service-body'].includes(config.buildType.id)
    },
    {
      id: 8,
      name: 'Work Body Internal Fit Outs',
      type: 'card-select',
      dataKey: 'workBodyInternalFitOuts',
      configKey: 'workBodyInternalFitOuts',
      template: 'work-body-internal-fit-outs',
      description: '',
      showIf: (config) => config.serviceBody?.id && [2].includes(config.serviceBody.id)
    },
    {
      id: 9,
      name: 'Passenger Side Fitout',
      type: 'card-select',
      dataKey: 'passengerFitout',
      configKey: 'passengerFitout',
      template: 'passenger-fitout',
      description: '',
      showIf: (config) =>
        (config.buildType && ['tray-canopy'].includes(config.buildType.id)) ||
        (config.serviceBody && config.serviceBody.id === 1),
    },
    {
      id: 10,
      name: 'Passenger Internal Accessories',
      type: 'multi-select',
      dataKey: 'passengerInternalAccessories',
      configKey: 'passengerInternalAccessories',
      template: 'passenger-internal-accessories',
      description: '',
      showIf: (config) => config.passengerFitout && ['empty-fitout'].includes(config.passengerFitout.id)
    },
    {
      id: 11,
      name: 'Driver Side Fitout',
      type: 'card-select',
      dataKey: 'driverFitout',
      configKey: 'driverFitout',
      template: 'driver-fitout',
      description: '',
      showIf: (config) =>
        (config.buildType && ['tray-canopy'].includes(config.buildType.id)) ||
        (config.serviceBody && config.serviceBody.id === 1),
    },
    /* {
       id: 12,
       name: 'Driver Internal Accessories',
       type: 'multi-select',
       dataKey: 'driverInternalAccessories',
       configKey: 'driverInternalAccessories',
       template: 'driver-internal-accessories',
       description: '',
       showIf: (config) => config.driverFitout && ['empty-fitout'].includes(config.driverFitout.id)
     },
 */
    {
      id: 12,
      name: 'Fridges',
      type: 'fridges',
      dataKey: 'fridges',
      configKey: 'fridges',
      template: 'fridges',
      description: '',
      showIf: (config) => config.buildType && ['tray-canopy', 'canopy', 'service-body'].includes(config.buildType.id)
    },
    {
      id: 13,
      name: 'Lighting',
      type: 'lighting-sound',
      dataKey: 'lightingSound',
      configKey: 'lightingSound',
      template: 'lighting-sound',
      description: '',
      showIf: (config) => config.buildType && ['tray-canopy', 'canopy', 'service-body'].includes(config.buildType.id)
    },
    {
      id: 14,
      name: 'Central Locking',
      type: 'central-locking',
      dataKey: 'centralLocking',
      configKey: 'centralLocking',
      template: 'central-locking',
      description: '',
      showIf: (config) => config.buildType && ['tray-canopy', 'canopy', 'service-body'].includes(config.buildType.id)
    },
    {
      id: 15,
      name: 'Colour Coding',
      type: 'colour-coding',
      dataKey: 'colourCoding',
      configKey: 'colourCoding',
      template: 'colour-coding',
      description: '',
      showIf: (config) => config.buildType && ['tray-canopy', 'canopy', 'service-body'].includes(config.buildType.id)
    },
    {
      id: 16,
      name: 'External Accessories',
      type: 'multi-select',
      dataKey: 'accessories',
      configKey: 'accessories',
      template: 'accessories',
      description: '',
      showIf: (config) => config.buildType && ['tray-canopy', 'service-body', 'service-body'].includes(config.buildType.id)
    },
    {
      id: 17,
      name: 'Roof Rack & Platforms',
      type: 'roof-rack',
      dataKey: 'roofRackPlatforms',
      configKey: 'roofRackPlatforms',
      template: 'roof-rack',
      description: '',
      showIf: (config) => config.buildType && ['tray-canopy', 'canopy', 'service-body'].includes(config.buildType.id)
    },
    {
      id: 18,
      name: 'Brackets',
      type: 'brackets',
      dataKey: 'brackets',
      configKey: 'brackets',
      template: 'brackets',
      description: '',
      showIf: (config) => config.roofRackPlatforms?.id && [1, 2, 3, 4, 5].includes(config.roofRackPlatforms.id)
    },
    {
      id: 19,
      name: 'Awnings',
      type: 'card-select',
      dataKey: 'awnings',
      configKey: 'awnings',
      template: 'awnings',
      description: '',
      showIf: (config) => config.buildType && ['tray-canopy', 'service-body'].includes(config.buildType.id)
    },
    {
      id: 20,
      name: 'Rooftop Tents',
      type: 'rooftop-tent',
      dataKey: 'rooftopTentAwnings',
      configKey: 'rooftopTentAwnings',
      template: 'rooftop-tent',
      description: '',
      showIf: (config) => config.buildType && ['tray-canopy', 'service-body'].includes(config.buildType.id)
    },
    {
      id: 21,
      name: 'Installation & Freight',
      type: 'multi-select',
      dataKey: 'freight',
      configKey: 'freight',
      template: 'freight',
      description: '',
      showIf: (config) => config.buildType && ['tray-only', 'tray-canopy', 'service-body'].includes(config.buildType.id)
    },
    {
      id: 22,
      name: 'Summary',
      type: 'summary',
      template: 'summary',
      description: 'Review your complete build and proceed to get a quote.'
    }
  ],
  awnings: [
    {
      id: 1,
      name: 'AS Awning – Shadow Master 180',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ScreenShot2024-08-12at10.13.18am.png?v=1723557244&width=900',
      description: '',
      price: 999,
      weight: 25,
      labourCost: 227.5

    },
    {
      id: 2,
      name: 'AS Awning – Shadow Master Square',
      image: 'https://autospec4x4.com.au/cdn/shop/files/Image_1_ec3ce6ba-2d04-4803-9202-749fd1d8203b.jpg?v=1723607717&width=640',
      description: '',
      price: 399,
      weight: 12.5,
      labourCost: 227.5
    }, 
    {
      id: 3,
      name: 'AS Awning – Shadow Master 270 - Passenger - D-Hole',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ScreenShot2024-08-12at10.13.06am.png?v=1723556968&width=900',
      description: '',
      price: 1299,
      weight: 32,
      labourCost: 227.5
    },
     {
      id: 4,
      name: 'AS Awning Bracket',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ScreenShot2024-08-12at10.13.06am.png?v=1723556968&width=900',
      description: '',
      price: 60,
      weight: 0,
      labourCost: 227.5,
      placeholder: true
    },
  ],
  states: [
    { company: 'Opposite Lock Cardiff', street: '31 Munibung Rd', state: 'NSW' },
    { company: 'Opposite Lock South Sydney', street: 'Unit 1, 405-411 W Botany St', state: 'NSW' },
    { company: 'Opposite Lock Wollongong', street: '1 Mineral Road', state: 'NSW' },
    { company: 'Opposite Lock Bathurst', street: '263 Stewart Street', state: 'NSW' },
    { company: 'Opposite Lock Nowra', street: 'Shop 5 218 Princess Hwy', state: 'NSW' },
    { company: 'Opposite Lock Tamworth', street: '1-5 Belmore street', state: 'NSW' },
    { company: 'Opposite Lock Dubbo', street: '36-42 Erskine St', state: 'NSW' },
    { company: 'Opposite Lock Wagga Wagga', street: '42 Hammond Avenue/ (new add 143 hamond ave)', state: 'NSW' },
    { company: 'Opposite Lock Broken Hill', street: '97A Oxide Street', state: 'NSW' },
    { company: 'Opposite Lock Lismore [New Store - Opening Soon!]', street: '228 Union St', state: 'NSW' },
    { company: 'Opposite Lock Darwin', street: '15 McCourt Rd', state: 'NT' },
    { company: 'Opposite Lock Arundel', street: '136 Kingston Drive', state: 'QLD' },
    { company: 'Opposite Lock Toowoomba', street: '18 Wylie St', state: 'QLD' },
    { company: 'Opposite Lock Beenleigh', street: '51 Logan River Road', state: 'QLD' },
    { company: 'Opposite Lock Ipswich', street: '246 Brisbane Road', state: 'QLD' },
    { company: 'Opposite Lock Slacks Creek', street: '3343 Pacific Highway', state: 'QLD' },
    { company: 'Opposite Lock Breakfast Creek', street: '7 Maud St', state: 'QLD' },
    { company: 'Opposite Lock Caboolture', street: '48 Beerburrum Road', state: 'QLD' },
    { company: 'Opposite Lock Sunshine Coast', street: '19 Latcham Drive', state: 'QLD' },
    { company: 'Opposite Lock Bundaberg', street: '106 Enterprise Street', state: 'QLD' },
    { company: 'Opposite Lock Rockhampton', street: '178 Denison Street', state: 'QLD' },
    { company: 'Opposite Lock Mackay', street: '2D Victoria St', state: 'QLD' },
    { company: 'Opposite Lock Townsville', street: '16 Civil Road', state: 'QLD' },
    { company: 'Opposite Lock Mt. Isa', street: 'Cnr Marian and Butler Streets', state: 'QLD' },
    { company: 'Opposite Lock Mt. Barker', street: '6 Dutton Road', state: 'SA' },
    { company: 'Opposite Lock Windsor Gardens', street: '498 North East Road', state: 'SA' },
    { company: 'Opposite Lock Noarlunga', street: '2 Seaman Road', state: 'SA' },
    { company: 'Opposite Lock Hobart', street: '3/4 Railway Circuit access via Kennedy Drive', state: 'TAS' },
    { company: 'Opposite Lock Wodonga', street: '87 Thomas Mitchell Drive', state: 'VIC' },
    { company: 'Opposite Lock Sale', street: '10 Wade Ct', state: 'VIC' },
    { company: 'Opposite Lock Echuca', street: '182 Annesley Street', state: 'VIC' },
    { company: 'Opposite Lock Traralgon', street: '319 Princes Hwy', state: 'VIC' },
    { company: 'Opposite Lock Epping', street: '26-38 Miller Street', state: 'VIC' },
    { company: 'Opposite Lock Bendigo', street: '49 King Street', state: 'VIC' },
    { company: 'Opposite Lock Swan Hill', street: '40 Campbell Street', state: 'VIC' },
    { company: 'Opposite Lock Cranbourne', street: '226 South Gippsland Hwy', state: 'VIC' },
    { company: 'Opposite Lock Sunbury', street: '106-108 Horne Street', state: 'VIC' },
    { company: 'Opposite Lock Ballarat', street: '210 Lexton St', state: 'VIC' },
    { company: 'Opposite Lock Kununurra', street: '1. Ivanhoe Road', state: 'WA' },
    { company: 'Opposite Lock Midland', street: '181 Great Eastern Highway', state: 'WA' },
    { company: 'Opposite Lock Bunbury', street: '6 Bourke Street', state: 'WA' },
    { company: 'Opposite Lock Welshpool', street: '35 Welshpool Road', state: 'WA' },
    { company: 'Opposite Lock Cockburn', street: '87 Armadale Road', state: 'WA' },
    { company: 'Out Of Town 4WD', street: '65 Northville Drive', state: 'NSW' },
    { company: '4WD Ute Extras / ARB Coffs Harbour ( Out Of Town 4wd Group )', street: '114A Pacific Highway', state: 'NSW' },
    { company: 'FSE Shepparton', street: '61 Mitchell Street Shepparton 3630', state: 'VIC' },
    { company: 'Full Bore 4x4 and automotive care', street: '18B Tarkin Ct, Bell Park VIC 3215', state: 'VIC' },
    { company: 'Rapid Supply', street: '6–8 Stony Rise Road, Devonport, Tasmania 7310', state: 'TAS' },
    { company: 'Goldfields Auto-Tech PTY LTD T/as Goldfields Off Road', street: '1/35 Great Eastern Highway', state: 'WA' }
  ],
  freight: [
    {
      id: 'tray-only-cost-freight',
      name: 'Freight Cost',
      price: 599,
      showIf: (config) => config.buildType && ['tray-only'].includes(config.buildType.id),
    },
    {
      id: 'tray-canopy-cost-freight',
      name: 'Freight Cost',
      price: 799,
      showIf: (config) => config.buildType && ['tray-canopy'].includes(config.buildType.id),
    },
    {
      id: 'tray-only-cost-installation',
      name: 'Installation Cost',
      price: 400,
      showIf: (config) => config.buildType && ['tray-only'].includes(config.buildType.id),
    },
    {
      id: 'tray-canopy-cost-installation',
      name: 'Installation Cost',
      price: 650,
      showIf: (config) => config.buildType && ['tray-canopy'].includes(config.buildType.id),
    },
    {
      id: 'quote-is-estimate',
      name: 'This quote is an estimate only and subject to final approval by Autospec 4x4 staff.',
      description: '',
      class: 'quote-estimate'
    },
    {
      id: 'eligible-for-pickup',
      name: 'You\'re eligible for free pickup from our local warehouse',
      description: 'Pickup',
      checkbox: true,
      pickup: true,
    },
    {
      id: 'tub-tray-removed',
      name: 'Please select any other installation requirements for your ute.',
      checkbox: false,
    },
    {
      id: 'tub-tray-removal',
      name: 'Tub/Tray Removal',
      description: 'I need my Tub/Tray removed',
      price: 100,
      checkbox: true,
    },
    {
      id: 'adblue-relocation',
      name: 'Adblue relocation',
      description: 'My vehicle has Adblue',
      price: 150,
      checkbox: true,
    },
    {
      id: 'reverse-camera-relocation',
      name: 'Reverse Camera Relocation',
      description: 'Next Gen Ranger/Amarok',
      price: 265,
      checkbox: true,
    },
    {
      id: 'reverse-sensor-relocation',
      name: 'Reverse Sensor Relocation',
      description: 'Next Gen Ranger/Amarok',
      price: 395,
      checkbox: true,
    },
    {
      id: 'blind-spot-sensor-relocation',
      name: 'Blind Spot Sensor Relocation',
      description: 'Next Gen/Amarok',
      price: 590,
      checkbox: true,
    }
  ],
  buildTypes: [
    {
      id: 'tray-only',
      name: 'Tray Only',
      description: '',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/image_31929c63-c653-4f32-8454-afa3135de920.jpg?v=1741159659',

    },
    {
      id: 'tray-canopy',
      name: 'Tray and Canopy',
      description: '',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/DSC06571_26385d94-dba0-4ac3-a350-c31397e30f50.jpg?v=1741159660',
      labourCost: 1280,
      freightCost: 799
    },


  ],

  vehicles: [
    {
      id: 1,
      name: 'Toyota Hilux - Dual Cab',
      image: 'https://placehold.co/400x300?text=Toyota+Hilux+DC',
      description: 'Dual Cab',
      price: 0,
      gvm: 3000,
      traySize: '1700',
    },
    {
      id: 2,
      name: 'Toyota Hilux - Space Cab',
      image: 'https://placehold.co/400x300?text=Toyota+Hilux-SC',
      description: 'Space Cab',
      price: 0,
      gvm: 3200,
      traySize: '2000',
    },
    {
      id: 3,
      name: 'Ford Ranger',
      image: 'https://placehold.co/400x300?text=Ford+Ranger',
      description: 'Dual Cab',
      price: 0,
      gvm: 3200,
      traySize: '1700',
    },
    {
      id: 4,
      name: 'Isuzu D-Max',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Dual Cab',
      price: 0,
      gvm: 2900,
      traySize: '1700',
    },
    {
      id: 5,
      name: '79 Series',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Dual Cab',
      price: 0,
      gvm: 2900,
      traySize: '1800',
    },
    {
      id: 6,
      name: 'Amarok',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Dual Cab',
      price: 0,
      gvm: 2900,
      traySize: '2000',
    },
    {
      id: 7,
      name: 'BT50 - Dual Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Dual Cab',
      price: 0,
      gvm: 2900,
      traySize: '1700',
    },
    {
      id: 8,
      name: 'BT50 - Space Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Space Cab',
      price: 0,
      gvm: 2900,
      traySize: '2000',
    },
    {
      id: 9,
      name: 'BT50 - Space Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Space Cab',
      price: 0,
      gvm: 2900,
      traySize: '2000',
    },
    {
      id: 10,
      name: 'Colorado - Dual Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Dual Cab',
      price: 0,
      gvm: 2900,
      traySize: '1700',
    },
    {
      id: 11,
      name: 'Colorado - Space Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Space Cab',
      price: 0,
      gvm: 2900,
      traySize: '2000',
    },
    {
      id: 12,
      name: 'DMax - Dual Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Space Cab',
      price: 0,
      gvm: 2900,
      traySize: '1700',
    },
    {
      id: 13,
      name: 'DMax - Space Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Space Cab',
      price: 0,
      gvm: 2900,
      traySize: '2000',
    },
    {
      id: 14,
      name: 'Hilux - Dual Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Dual Cab',
      price: 0,
      gvm: 2900,
      traySize: '1700',
    },
    {
      id: 15,
      name: 'Hilux - Space Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Space Cab',
      price: 0,
      gvm: 2900,
      traySize: '2000',
    },
    {
      id: 16,
      name: 'Navara - Dual Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Dual Cab',
      price: 0,
      gvm: 2900,
      traySize: '1700',
    },
    {
      id: 17,
      name: 'Navara - Space Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Space Cab',
      price: 0,
      gvm: 2900,
      traySize: '2000',
    },
    {
      id: 18,
      name: 'Ranger - Dual Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Dual Cab',
      price: 0,
      gvm: 2900,
      traySize: '1700',
    },
    {
      id: 19,
      name: 'Ranger - Space Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Space Cab',
      price: 0,
      gvm: 2900,
      traySize: '2000',
    },
    {
      id: 20,
      name: 'Triton - Dual Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Dual Cab',
      price: 0,
      gvm: 2900,
      traySize: '1700',
    },
    {
      id: 21,
      name: 'Triton - Space Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Space Cab',
      price: 0,
      gvm: 2900,
      traySize: '2000',
    },
    {
      id: 22,
      name: 'GWM Cannon - Dual Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Dual Cab',
      price: 0,
      gvm: 2900,
      traySize: '1700',
    },
    {
      id: 23,
      name: 'LDV T60 - Dual Cab',
      image: 'https://placehold.co/400x300?text=Isuzu+D-Max',
      description: 'Dual Cab',
      price: 0,
      gvm: 2900,
      traySize: '1700',
    }


  ],
  workBodyInternalFitOuts: [
    {
      id: 1,
      name: '3 Teir Adjustable Shelving',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC06095.jpg?v=1734048585&width=900',
      price: 1390,
      description: '',
      weight: 0,
    },
    {
      id: 2,
      name: 'Work Body Drawer Fit Out',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC06095.jpg?v=1734048585&width=900',
      price: 1790,
      description: '',
      weight: 0,
    },
    {
      id: 3,
      name: 'I\'ll take an empty work body',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC06095.jpg?v=1734048585&width=900',
      price: 0,
      description: '',
      weight: 0,
    }
  ],
  trays: [
    {
      id: 1,
      name: '1700mm Tray',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC06095.jpg?v=1734048585&width=900',
      price: 5039,
      description: 'AS Aluminium Dual Cab Tray with Trundle - 1700mm - Matte Black',
      weight: 150,
      traySize: '1700',
      labourCost: 780,
      freightCost: 599
    },
    {
      id: 2,
      name: '2000mm Tray',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC06095.jpg?v=1734048585&width=900',
      price: 5679,
      description: 'AS Aluminium Dual Cab Tray with Trundle - 2000mm - Matte Black',
      weight: 150,
      traySize: '2000',
      labourCost: 780,
      freightCost: 599
    },
    {
      id: 3,
      name: '2400mm Tray',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC06095.jpg?v=1734048585&width=900',
      price: 6229,
      description: 'AS Aluminium Dual Cab Tray with Trundle - 2400mm - Matte Black',
      weight: 150,
      traySize: '2400',
      labourCost: 780,
      freightCost: 599
    },

  ],

  traysBonus: [
    {
      id: 'tray-bonus-1',
      name: 'AS Aluminium Headboard - Matte Black',
      image: 'https://autospec4x4.com.au/cdn/shop/files/AS_Aluminium_Headboard_-_Matte_Black_-_1.jpg?v=1724199689&width=900',
      price: 1089,
      description: 'This headboard is built to last, handling whatever your workday or weekend adventures throw at it',
      weight: 42.5,
      selected: true,
      checkbox: true,
      labourCost: 390,
      required: true

    },
    {
      id: 'tray-bonus-2',
      name: 'AS 32L Headboard with Water Tank',
      image: 'https://autospec4x4.com.au/cdn/shop/files/IMG_9081_5af50de4-fa05-44e9-bb24-278830e90a7f.png?v=1723591626&width=900',
      price: 569,
      description: 'The ideal solution for utilizing unused space in your ute tray. ',
      weight: 0,
      selected: true,
      checkbox: true,
      labourCost: 390,
      required: true
    },
    {
      id: 'as-water-pump',
      name: 'AS Water Pump',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/autospec-white_png.png?v=1739860494',
      price: 49,
      desription: '',
      weight: 110,
      checkbox: true,
      placeholder: true,
      labourCost: 65,
      required: true
    },
  ],

  serviceBody: [
    {
      id: 'empty-fitout',
      name: 'Service Bodies',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC05025.jpg?v=1732760663&width=900',
      price: 1190,
      description: '',
      weight: 0,
      size: 1000
    },
    {
      id: 'empty-fitout',
      name: 'Work Bodies',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC05025.jpg?v=1732760663&width=900',
      price: 1190,
      description: '',
      weight: 0,
      size: 1000
    },

  ],

  canopies: [
    {
      id: 1,
      name: '1000mm Canopy',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC05025.jpg?v=1732760663&width=900',
      price: 3529,
      description: 'AS Aluminium Canopy 1000mm - Matte Black',
      weight: 122, // Weight in kg
      size: 1000,
      labourCost: 520,
      freightCost: 399
    },
    {
      id: 2,
      name: '1400mm Canopy',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC05562.jpg?v=1732759871&width=900',
      price: 4329,
      description: 'AS Aluminium Canopy 1400mm - Matte Black',
      weight: 160, // Weight in kg
      size: 1400,
      labourCost: 520,
      freightCost: 399
    },
    {
      id: 3,
      name: '1700mm Canopy',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC05117.jpg?v=1732758634&width=900',
      price: 4979,
      description: 'AS Aluminium Canopy 1700mm - Matte Black',
      weight: 178, // Weight in kg
      size: 1700,
      labourCost: 520,
      freightCost: 399
    }
  ],
  traySides: [
    {
      id: 1,
      name: '300mm Tray Sides',
      image: 'https://autospec4x4.com.au/cdn/shop/files/IMG_9118_ed6257e9-7cb5-4cd3-b85c-9a10586e94b6.png?v=1723611378&width=900',
      price: 699,
      description: 'AS Heavy Duty Tray Side Kit - 300mm - Matte Black',
      weight: 13.1,
      size: '300',
      labourCost: 65
    },
    {
      id: 2,
      name: '600mm Tray Sides',
      image: 'https://autospec4x4.com.au/cdn/shop/files/IMG_9118_ed6257e9-7cb5-4cd3-b85c-9a10586e94b6.png?v=1723611378&width=900',
      price: 749,
      description: 'AS Heavy Duty Tray Side Kit - 600mm - Matte Black',
      weight: 16.7,
      size: '600',
      labourCost: 65
    },
    {
      id: 3,
      name: '700mm Tray Sides',
      image: 'https://autospec4x4.com.au/cdn/shop/files/IMG_9118_ed6257e9-7cb5-4cd3-b85c-9a10586e94b6.png?v=1723611378&width=900',
      price: 769,
      description: 'AS Heavy Duty Tray Side Kit - 700mm - Matte Black',
      weight: 16.6,
      size: '700',
      labourCost: 65
    },
    {
      id: 4,
      name: '1000mm Tray Sides',
      image: 'https://autospec4x4.com.au/cdn/shop/files/IMG_9118_ed6257e9-7cb5-4cd3-b85c-9a10586e94b6.png?v=1723611378&width=900',
      price: 829,
      description: 'AS Heavy Duty Tray Side Kit - 1000mm - Matte Black',
      weight: 19.4,
      size: '1000',
      labourCost: 65
    },
    {
      id: 5,
      name: '1700mm Tray Sides',
      image: 'https://autospec4x4.com.au/cdn/shop/files/IMG_9075_a69f4234-da75-4742-8cb8-62e9e961b4cf.jpg?v=1723610271&width=900',
      price: 959,
      description: 'AS Heavy Duty Tray Side Kit - 1700mm - Matte Black',
      weight: 22.5,
      size: '1700',
      labourCost: 65
    },
    {
      id: 6,
      name: '2000mm Tray Sides',
      image: 'https://autospec4x4.com.au/cdn/shop/files/IMG_9118_ed6257e9-7cb5-4cd3-b85c-9a10586e94b6.png?v=1723611378&width=900',
      price: 1009,
      description: 'AS Heavy Duty Tray Side Kit - 2000mm - Matte Black',
      weight: 27.5,
      size: '2000',
      labourCost: 65
    },
    {
      id: 7,
      name: '2400mm Tray Sides',
      image: 'https://autospec4x4.com.au/cdn/shop/files/IMG_9118_ed6257e9-7cb5-4cd3-b85c-9a10586e94b6.png?v=1723611378&width=900',
      price: 1089,
      description: 'AS Heavy Duty Tray Side Kit - 2000mm - Matte Black',
      weight: 30,
      size: '2400',
      labourCost: 65
    },
  ],

  passengerFitout: [
    {
      id: 'empty-fitout',
      name: 'Empty Fitout',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC05644.jpg',
      description: '',
      price: 0,
      weight: 0,
      size: 0,
    },
    {
      id: 'fitout-one-1700',
      name: '1700mm Setup 1',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/DSC05930_85b607e7-5de3-49fb-bc8a-facb6b98a87c.jpg?v=1741159660',
      description: '<ul><li>Allowance for 12 Volt Package</li><li>85L Fridge Cage</li><li>Kitchen Unit</li><li>Pantry 200</li></ul><span class="inclusion-message">*Does not include fridge or 12v setup</span>',
      price: 1542,
      weight: 15,
      size: 1700,
      labourCost: 65
    },
    {
      id: 'fitout-two-1700',
      name: '1700mm Setup 2',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/DSC09198.jpg?v=1741159660',
      description: '<ul><li>Allowance for 12 Volt Package</li><li>65L Fridge Cage + Drawer Cage</li><li>Medium Drawer</li><li>Pantry 200</li></ul><span class="inclusion-message">*Does not include fridge or 12v setup</span>',
      price: 1542,
      weight: 0,
      size: 1700,
      labourCost: 65
    },
    {
      id: 'fitout-one-1400',
      name: '1400mm Setup 1',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/DSC09198.jpg?v=1741159660',
      description: '<ul><li>Allowance for 12 Volt Package</li><li>85L Fridge Cage + Fridge Cage</li><li>Kitchen Unit</li><li>Micro Pantry (Kitchen Unit)</li></ul><span class="inclusion-message">Does not include fridge or Battery*</span>',
      price: 1316,
      weight: 0,
      size: 1400,
      labourCost: 65
    },
    {
      id: 'fitout-two-1400',
      name: '1400mm Setup 2',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/DSC09198.jpg?v=1741159660',
      description: '<ul><li>Allowance for 12 Volt Package</li><li>65L Fridge Cage + Fridge Cage</li><li>Kitchen Unit</li></ul><span class="inclusion-message">Does not include fridge or Battery*</span>',
      price: 1302,
      weight: 0,
      size: 1400,
      labourCost: 65
    },
    {
      id: 'fitout-one-1000',
      name: '1000mm Setup 1',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/DSC09198.jpg?v=1741159660',
      description: '<ul><li>12 Volt Case</li><li>85L Fridge Cage</li><li>Pantry 125</li></ul><span class="inclusion-message">Does not include fridge or Battery*</span>',
      price: 896,
      weight: 0,
      size: 1000,
      labourCost: 65
    },
    {
      id: 'fitout-two-1000',
      name: '1000mm Setup 2',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/DSC09198.jpg?v=1741159660',
      description: '<ul><li>12 Volt Case</li><li>65L Fridge Cage</li><li>Pantry 125</li></ul><span class="inclusion-message">Does not include fridge or Battery*</span>',
      price: 872,
      weight: 0,
      size: 1000,
      labourCost: 65
    },

  ],
  passengerInternalAccessories: [
    {
      id: 'passenger-accessories-1',
      name: 'Passenger Accessories 1',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/autospec-white_png.png?v=1739860494',
      description: '',
      price: 1000,
      weight: 100,
      checkbox: true,
      placeholder: true,
      labourCost: 65
    },
    {
      id: 'passenger-accessories-2',
      name: 'Passenger Accessories 2',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/DSC05930_85b607e7-5de3-49fb-bc8a-facb6b98a87c.jpg?v=1741159660',
      description: '',
      price: 1200,
      weight: 100,
      checkbox: true,
      labourCost: 65
    },
    {
      id: 'passenger-accessories-3',
      name: 'Passenger Accessories 3',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/DSC09198.jpg?v=1741159660',
      description: '',
      price: 0,
      weight: 0,
      checkbox: true,
      labourCost: 65
    }
  ],
  driverFitout: [
    {
      id: 'empty-fitout',
      name: 'Empty Fitout',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC05644.jpg',
      description: '',
      price: 0,
      weight: 0,
    },
  ],

  driverInternalAccessories: [
    {
      id: 'driver-accessories-1',
      name: 'Driver Accessories 1',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/autospec-white_png.png?v=1739860494',
      description: '',
      price: 1000,
      weight: 200,
      checkbox: true,
      placeholder: true,
    },
    {
      id: 'driver-accessories-2',
      name: 'Driver Accessories 2',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/DSC05930_85b607e7-5de3-49fb-bc8a-facb6b98a87c.jpg?v=1741159660',
      description: '',
      price: 1200,
      weight: 100,
      checkbox: true,
    },
    {
      id: 'driver-accessories-3',
      name: 'Driver Accessories 3',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/DSC09198.jpg?v=1741159660',
      description: '',
      price: 0,
      weight: 500,
      checkbox: true,
    }
  ],
  dogBoxConversion: [
    {
      id: 1,
      name: 'Dogbox 1',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/autospec-white_png.png?v=1739860494',
      description: '',
      price: 1000,
      weight: 70,
      placeholder: true,
    },
    {
      id: 2,
      name: 'Dogbox 1',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/autospec-white_png.png?v=1739860494',
      description: '',
      price: 1200,
      weight: 90,
      placeholder: true,
    },
  ],
  voltAndOven: [
    {
      id: 1,
      name: 'The Tourer 12 Volt Package with 200Ah Battery',
      image: 'https://autospec4x4.com.au/cdn/shop/files/as-12v.png?v=1736910995&width=640',
      description: '<ul><li>Custom Aluminium Powder Coated Black Case</li><li>Autospec 200Ah Battery</li><li>Renogy 12V 50A DC-DC On-Board Battery Charger with MPPT</li><li>Renogy 2000W 12V to 230V/240V Pure Sine Wave Inverter (with UPS)</li><li>Renogy 300A Battery Monitor with Shunt</li><li>RCM-BT2 - Renogy BT-2 Bluetooth Module</li><li>2 x Black GPO</li><li>8 Gang Switch</li><li>2 x Cig Socket + Dual USB</li><li>Dual 50A Anderson Plugs</li></ul>',
      price: 5499,
      weight: 0,
      labourCost: 260,
      freightCost: 199
    },
    {
      id: 2,
      name: 'The Tourer 12 Volt Package with 300Ah Battery',
      image: 'https://autospec4x4.com.au/cdn/shop/files/as-12v.png?v=1736910995&width=640',
      description: '<ul><li>Custom Aluminium Powder Coated Black Case</li><li>Renogy 12V 50A DC-DC On-Board Battery Charger with MPPT</li><li>Renogy 2000W 12V to 230V/240V Pure Sine Wave Inverter (with UPS)</li><li>Renogy 300A Battery Monitor with Shunt</li><li>RCM-BT2 - Renogy BT-2 Bluetooth Module</li><li>2 x Black GPO</li><li>8 Gang Switch</li><li>2 x Cig Socket + Dual USB</li><li>Dual 50A Anderson Plugs</li></ul>',
      price: 6289,
      weight: 0,
      labourCost: 260,
      freightCost: 199
    },
    {
      id: 3,
      name: 'The Weekender 12 Volt Package with 100Ah Battery',
      image: 'https://autospec4x4.com.au/cdn/shop/files/as-12v.png?v=1736910995&width=640',
      description: '<ul><li>Custom Aluminium Powder Coated Black Case</li><li>Autospec 100Ah Battery</li><li>Renogy 12V 30A DC-DC On-Board Battery Charger with MPPT</li><li>Renogy 1000W 12V to 230V/240V Pure Sine Wave Inverter (with UPS)</li><li>Renogy 500A Battery Monitor with Shunt</li><li>RCM-BT2 - Renogy BT-2 Bluetooth Module</li><li>2 x Black GPO</li><li>8 Gang Switch</li><li>2 x Cig Socket + Dual USB</li><li>Dual 50A Anderson Plugs</li></ul>',
      price: 4199,
      weight: 0,
      labourCost: 260,
      freightCost: 199
    },
    {
      id: 4,
      name: 'The Weekender 12 Volt Package with 200Ah Battery',
      image: 'https://autospec4x4.com.au/cdn/shop/files/as-12v.png?v=1736910995&width=640',
      description: '<ul><li>Autospec 200Ah Battery</li><li>Custom Aluminium Powder Coated Black Case</li><li>Custom Aluminium Powder Coated Black Case</li><li>Renogy 12V 30A DC-DC On-Board Battery Charger with MPPT</li><li>Renogy 1000W 12V to 230V/240V Pure Sine Wave Inverter (with UPS)</li><li>Renogy 500A Battery Monitor with Shunt</li><li>RCM-BT2 - Renogy BT-2 Bluetooth Module</li><li>2 x Black GPO</li><li>8 Gang Switch</li><li>2 x Cig Socket + Dual USB</li><li>Dual 50A Anderson Plugs</li></ul>',
      price: 4799,
      weight: 0,
      labourCost: 260,
      freightCost: 199
    },
    {
      id: 5,
      name: 'The Weekender 12 Volt Package with 300Ah Battery',
      image: 'https://autospec4x4.com.au/cdn/shop/files/as-12v.png?v=1736910995&width=640',
      description: '<ul><li>Autospec 300Ah Battery</li><li>Custom Aluminium Powder Coated Black Case</li><li>Custom Aluminium Powder Coated Black Case</li><li>Renogy 12V 30A DC-DC On-Board Battery Charger with MPPT30V/240V Pure Sine Wave Inverter (with UPS)</li><li>Renogy 500A Battery Monitor with Shunt</li><li>RCM-BT2 - Renogy BT-2 Bluetooth Module</li><li>2 x Black GPO</li><li>8 Gang Switch</li><li>2 x Cig Socket + Dual USB</li><li>Dual 50A Anderson Plugs</li></ul>',
      price: 5602,
      weight: 0,
      labourCost: 260,
      freightCost: 199
    },
    {
      id: 6,
      name: 'Case Only - DIY Fitout',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/autospec-white_png.png?v=1739860494',
      description: '',
      price: 499,
      weight: 0,
      placeholder: true,
      labourCost: 260,
      freightCost: 199
    },
  ],

  fridges: [
    {
      id: 1,
      name: 'Bushman DC85-X',
      image: 'https://bushman.com.au/wp-content/uploads/2018/08/Bushman_DC65_NewCrisper.jpg',
      description: '',
      price: 1495,
      weight: 0,
      labourCost: 130
    },
    {
      id: 2,
      name: 'Bushman DC65-X 65 Caravan Fridge',
      image: 'https://bushman.com.au/wp-content/uploads/2018/08/Bushman_DC65_NewCrisper.jpg',
      description: '',
      price: 1295,
      weight: 0,
      labourCost: 130
    }
  ],
  lightingSound: [
    {
      id: '60cm-12-volt-led',
      name: '60cm 12 Volt LED rigid strip light (Red & White)',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/autospec-white_png.png?v=1739860494',
      description: '',
      price: 49,
      weight: 0,
      placeholder: true,
      labourCost: 130,
      quantitySelector: true,
      checkbox: true
    },
    {
      id: '90cm-12-volt-led',
      name: '90cm 12 Volt LED rigid strip light (Red & White)',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/autospec-white_png.png?v=1739860494',
      description: '',
      price: 69,
      weight: 0,
      placeholder: true,
      labourCost: 130,
      quantitySelector: true,
      checkbox: true,
    },
  ],

  centralLocking: [
    {
      id: 1,
      name: 'Canopy Central Locking',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/autospec-white_png.png?v=1739860494',
      description: '4 x Whale tail locks connected to your vehicle factory remote.',
      price: 1100,
      weight: 0,
      placeholder: true,
      labourCost: 550
    }
  ],

  colourCoding: [
    {
      id: 1,
      name: 'Undertray Doors 2Pac Colour Coded',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/Screenshot_2025-02-24_at_1.05.14_pm_200x200.png?v=1740362725',
      description: 'AS Undertray Doors - 2Pac Colour Coded',
      price: 340,
      weight: 0,
      labourCost: 550
    },
    {
      id: 2,
      name: '1000 Canopy Door 2Pac Colour Coded',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/Screenshot_2025-02-24_at_12.54.16_pm_200x200.png?v=1740362201',
      description: 'AS 1000 Canopy Door - 2Pac Colour Coded',
      price: 1430,
      weight: 0,
      labourCost: 550
    },
    {
      id: 3,
      name: '1400 Canopy Door 2Pac Colour Coded',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/c4f89003-c8e2-4cba-ad1b-be903287d3e3_200x200.jpg?v=1740368937',
      description: 'AS 1400 Canopy Door - 2Pac Colour Coded',
      price: 1590,
      weight: 0,
      labourCost: 550
    },
    {
      id: 3,
      name: '1700 Canopy Door 2Pac Colour Coded',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/Screenshot_2025-02-24_at_12.54.16_pm_200x200.png?v=1740362201',
      description: 'AS 1700 Canopy Door - 2Pac Colour Coded',
      price: 1690,
      weight: 0,
      labourCost: 550
    },
  ],
  rooftopTentAwnings: [
    {
      id: 1,
      name: 'Roof Top Tent 1.2 High Roof',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ScreenShot2024-08-12at10.13.27am.png?v=1723555597&width=900',
      description: 'AS Roof Top Tent - The Sky Lodge 1.2 (Premium High Roof)',
      price: 3799,
      weight: 82,
      labourCost: 130,
      freightCost: 199
    },
    {
      id: 2,
      name: 'Roof Top Tent 1.5',
      image: 'https://autospec4x4.com.au/cdn/shop/files/RTT1.5.png?v=1732256640&width=900',
      description: 'AS Roof Top Tent - The Sky Lodge Deluxe 1.5',
      price: 4399,
      weight: 94,
      labourCost: 130,
      freightCost: 199
    },

  ],

  roofRackPlatforms: [
    {
      id: 1,
      name: 'Platform Rack 1350x1250',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASAluminiumPlatformRack.jpg?v=1725323231&width=900',
      description: 'AS Aluminium Platform Rack 1350x1250',
      price: 719,
      weight: 28,
      labourCost: 130,
      freightCost: 199
    },
    {
      id: 2,
      name: 'Platform Rack 1500x1250',
      image: 'https://autospec4x4.com.au/cdn/shop/files/67f87573-8a85-4479-a1a6-cee5520f7639.jpg?v=1738833391&width=900',
      description: 'AS Aluminium Platform Rack 1500x1250',
      price: 859,
      weight: 28,
      labourCost: 130,
      freightCost: 199
    },
    {
      id: 3,
      name: 'Platform Rack 1800x1250',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASAluminiumPlatformRack_6ab8dcac-6db8-4008-9a55-081d416a0758.jpg?v=1725323250&width=900',
      description: 'AS Aluminium Platform Rack 1800x1250',
      price: 999,
      weight: 24.5,
      labourCost: 130,
      freightCost: 199
    },
    {
      id: 4,
      name: 'Platform Rack 2200x1250',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASAluminiumPlatformRack_6ab8dcac-6db8-4008-9a55-081d416a0758.jpg?v=1725323250&width=900',
      description: 'AS Aluminium Platform Rack 2200x1250',
      price: 1209,
      weight: 29.5,
      labourCost: 130,
      freightCost: 199
    },
    {
      id: 5,
      name: 'Platform Rack 2200x1425',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASAluminiumPlatformRack_135ad7d3-b5e6-4ee0-8d01-e543136481f3.jpg?v=1725323292&width=900',
      description: 'AS Aluminium Platform Rack 2200x1425',
      price: 1389,
      weight: 3.5,
      labourCost: 130,
      freightCost: 199
    },

  ],

  brackets: [
    {
      id: 1,
      name: 'AS Backbone Mounting Bracket - Ford Ranger Next Gen',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 149,
      description: '',
      weight: 6.5,
    },
    {
      id: 2,
      name: 'AS Backbone Mounting Bracket - Ford Ranger PX',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 149,
      description: '',
      weight: 5.3,
    },
    {
      id: 3,
      name: 'AS Backbone Mounting Bracket - GWM Cannon',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 149,
      description: '',
      weight: 7.5,
    },
    {
      id: 4,
      name: 'AS Backbone Mounting Bracket - Hilux N70',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 149,
      description: '',
      weight: 4.9,
    },
    {
      id: 5,
      name: 'AS Backbone Mounting Bracket - Hilux N80',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 149,
      description: '',
      weight: 2,
    },
    {
      id: 6,
      name: 'AS Backbone Mounting Bracket - Isuzu D-MAX 2013+',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 149,
      description: '',
      weight: 5,
    },
    {
      id: 7,
      name: 'AS Backbone Mounting Bracket - Mitsubishi Triton 06 - 14',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 149,
      description: '',
      weight: 4.9,
    },
    {
      id: 8,
      name: 'AS Backbone Mounting Bracket - Mitsubishi Triton MQ MR 2015 - 2024',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 149,
      description: '',
      weight: 4.4,
    },
    {
      id: 9,
      name: 'AS Backbone Mounting Bracket - Nissan NP300 Navara',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 149,
      description: '',
      weight: 5.3,
    },
    {
      id: 10,
      name: 'AS Backbone Mounting Bracket - Volkswagen Amarok 11-20',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 149,
      description: '',
      weight: 2,
    },
    {
      id: 11,
      name: 'AS Backbone Mounting Bracket for 1800mm x 1250mm Platform - Isuzu MU-X',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 209,
      description: '',
      weight: 2,
    },
    {
      id: 12,
      name: 'AS Backbone Mounting Bracket for 1800mm x 1250mm Platform - Land Rover Discovery 5',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 209,
      description: '',
      weight: 7.3,
    },
    {
      id: 13,
      name: 'AS Backbone Mounting Bracket for 1800mm x 1250mm Platform - Toyota 4 Runner 2019+',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 209,
      description: '',
      weight: 2,
    },
    {
      id: 14,
      name: 'AS Backbone Mounting Bracket for 1800mm x 1250mm Platform - Toyota Fortuner',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 209,
      description: '',
      weight: 2,
    },
    {
      id: 15,
      name: 'AS Backbone Mounting Bracket for 1800mm x 1250mm Platform - Toyota Landcruiser 200 Series',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 209,
      description: '',
      weight: 8,
    },
    {
      id: 16,
      name: 'AS Backbone Mounting Bracket for 1800mm x 1250mm Platform - Toyota Prado 120',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 209,
      description: '',
      weight: 7.3,
    },
    {
      id: 17,
      name: 'AS Backbone Mounting Bracket for 1800mm x 1250mm Platform - Toyota Prado 150',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 209,
      description: '',
      weight: 7.2,
    },
    {
      id: 18,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1250mm Platform - Ford Everest (2015-2020)',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 8.4,
    },
    {
      id: 19,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1250mm Platform - Isuzu MU-X',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 10.5,
    },
    {
      id: 20,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1250mm Platform - Land Rover Defender 2020',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 15.2,
    },
    {
      id: 21,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1250mm Platform - Land Rover Discovery 4',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 8.6,
    },
    {
      id: 22,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1250mm Platform - Mitsubishi Pajero V97/73',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 2,
    },
    {
      id: 23,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1250mm Platform - Toyota FJ Cruiser',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 8.1,
    },
    {
      id: 24,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1250mm Platform - Toyota Fortuner',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 9.4,
    },
    {
      id: 25,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1250mm Platform - Toyota Landcruiser 200 Series',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 8.8,
    },
    {
      id: 26,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1250mm Platform - Toyota Prado 120',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 8.4,
    },
    {
      id: 27,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1250mm Platform - Toyota Prado 150',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 8.4,
    },
    {
      id: 28,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1425mm Platform - Jeep Wrangler JK',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 21.1,
    },
    {
      id: 29,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1425mm Platform - Nissan Patrol Y62',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 9.1,
    },
    {
      id: 30,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1425mm Platform - Toyota Landcruiser 100 Series',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 9.4,
    },
    {
      id: 31,
      name: 'AS Backbone Mounting Bracket for 2200mm x 1425mm Platform - Toyota Landcruiser 300 Series',
      image: 'https://autospec4x4.com.au/cdn/shop/files/ASBackboneMountingBracket.jpg?v=1725323405&width=320',
      price: 259,
      description: '',
      weight: 9.6,
    },
  ],

  accessories: [
    {
      id: 'spare-wheel-carrier',
      name: 'Spare Wheel Carrier',
      image: 'https://autospec4x4.com.au/cdn/shop/files/Spare_Tyre_Mockup_2_f6adfd49-e802-4b75-8f40-6c99de040b70.jpg?v=1723609406&width=900',
      price: 289,
      description: 'AS Spare Wheel Carrier - Matte Black',
      weight: 15,
      checkbox: true,
      labourCost: 65,
      freightCost: 30
    },
    {
      id: 'lockable-jerry-can-holder',
      name: 'Lockable Jerry Can Holder',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC04072.jpg?v=1732251350&width=900',
      price: 299,
      description: 'AS Lockable Jerry Can Holder - Matte Black',
      weight: 12,
      checkbox: true,
      labourCost: 65,
      freightCost: 30
    },
    {
      id: 'jerry-can-holder',
      name: 'Jerry Can Holder',
      image: 'https://autospec4x4.com.au/cdn/shop/files/DSC04072.jpg?v=1732251350&width=900',
      price: 189,
      description: 'AS Jerry Can Holder - Matte Black',
      weight: 5,
      checkbox: true,
      labourCost: 65,
      freightCost: 30
    },
    {
      id: 'rear-ladder',
      name: 'Rear Ladder',
      image: 'https://autospec4x4.com.au/cdn/shop/files/as-ladder_2f52cb0c-00ac-4f5a-92a1-9c9d877b50e0.jpg?v=1724110547&width=900',
      price: 369,
      description: 'AS Rear Ladder - Matte Black',
      weight: 10.5,
      checkbox: true,
      labourCost: 65,
      freightCost: 30
    },
    {
      id: 'as-rear-hoop-850',
      name: 'AS Rear Hoop (850mm Height)',
      image: 'https://autospec4x4.com.au/cdn/shop/files/RearHoop1_846f20ba-7d7b-4732-8ac5-3ca144568f45.jpg?v=1724034396&width=900',
      price: 359,
      desription: 'Elevate your vehicle\'s functionality with the Autospec Rear Hoop, standing tall at 850mm',
      weight: 8,
      checkbox: true,
      labourCost: 130,
      freightCost: 30
    },
    {
      id: 'as-rear-hoop-rear-hoop-79-series',
      name: 'AS Rear Hoop Rear 79 Series (975mm Height)',
      image: 'https://autospec4x4.com.au/cdn/shop/files/RearHoop1_846f20ba-7d7b-4732-8ac5-3ca144568f45.jpg?v=1724034396&width=900',
      price: 399,
      desription: 'Elevate your 79 Series with the Autospec Rear Hoop, standing tall at 975mm.',
      weight: 0,
      checkbox: true,
      labourCost: 65,
      freightCost: 30
    },
    {
      id: 'as-two-piece-spoiler',
      name: 'AS Two Piece Spoiler - Matte Black',
      image: 'https://autospec4x4.com.au/cdn/shop/files/RearSpoiler1Piece_ec51f8e0-6bf7-4999-aefe-1728de313f03.jpg?v=1724034656&width=900',
      price: 89,
      desription: 'Elevate the look and functionality of your vehicle with the Autospec Two Piece Spoiler.',
      weight: 1.6,
      checkbox: true,
      labourCost: 130,
      freightCost: 30
    },
    {
      id: 'as-one-piece-spoiler-matte-black',
      name: 'AS One Piece Spoiler - Matte Black',
      image: 'https://autospec4x4.com.au/cdn/shop/files/RearSpoiler1Piece_ec51f8e0-6bf7-4999-aefe-1728de313f03.jpg?v=1724034656&width=900',
      price: 139,
      desription: 'Elevate the look and functionality of your vehicle with the Autospec One Piece Spoiler.',
      weight: 3.7,
      checkbox: true,
      labourCost: 130,
      freightCost: 30
    },
    {
      id: 'as-jack-off-legs',
      name: 'AS Jack Off Legs - Type A',
      image: 'https://cdn.shopify.com/s/files/1/0580/6050/5263/files/autospec-white_png.png?v=1739860494',
      price: 559,
      desription: '',
      weight: 0,
      checkbox: true,
      placeholder: true,
      labourCost: 65,
      freightCost: 30
    },

  ]
};